backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# when using the default proxy server port
local_backend: true

# This line should *not* be indented
# publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: static/images
public_folder: /images

display_url: https://www.flutterdevcamp.com/
media_library:
  name: cloudinary
  config:
    cloud_name: flutterdevcamp
    api_key: 664686945695341

collections:
  - name: 'workshops'
    label: 'Workshops'
    slug: '{{slug}}'
    description: 'Workshop dates, location, and presenter information.'
    folder: 'website/src/pages/workshops'
    create: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'workshop',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: Featured Image,
          name: featuredImage,
          required: false,
          hint: "If an image isn't specified, a default placeholder image will be used",
          widget: image,
        }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Topic', name: 'topic', widget: 'text' }
      - {
          label: 'Duration in Hours',
          name: 'duration',
          widget: 'number',
          default: 2,
        }
      - {
          label: 'Number Of Lectures',
          name: 'numberOfLectures',
          widget: 'number',
          default: 4,
        }
      - {
          label: 'Max Number of Students',
          name: 'maxNumberofStudents',
          widget: 'number',
          default: 40,
        }
      - {
          label: 'Skill Level',
          name: 'skillLevel',
          widget: text,
          default: "Basic",
        }
      - {
          label: 'Language',
          name: 'language',
          widget: text,
          default: "English",
        } 
      - {
          label: 'Format Inperson',
          name: 'formatInperson',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Format Online',
          name: 'formatOnline',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Show on footer',
          name: 'showonfooter',
          widget: 'boolean',
          default: false,
        }
      - {
          label: Presenters,
          name: presenters,
          required: true,
          widget: list,
          fields:
            [
              { label: Name, name: name, required: true, widget: string },
              {
                label: Presentation Title,
                name: presentationTitle,
                required: false,
                widget: string,
              },
              {
                label: Image,
                name: image,
                required: false,
                hint: "If an image isn't specified, a default headshot placeholder image will be used",
                widget: image,
              },
              { label: Text, name: text, required: true, widget: text },
              {
                label: Links,
                name: links,
                required: false,
                widget: list,
                fields:
                  [
                    { label: Text, name: linkText, widget: string },
                    { label: URL, name: linkURL, widget: string },
                  ],
              },
            ],
        }
      - {
          label: 'Location',
          name: 'location',
          required: true,
          widget: 'object',
          fields:
            [
              { label: 'Name', name: 'name', widget: 'string' },
              { label: 'Google Maps Link', name: 'mapsLink', widget: 'string' },
              {
                label: 'Latitude',
                name: 'mapsLatitude',
                widget: 'number',
                valueType: 'float',
              },
              {
                label: 'Longitude',
                name: 'mapsLongitude',
                widget: 'number',
                valueType: 'float',
              },
            ],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'website/src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              label: 'Main Image',
              name: 'mainImage',
              widget: 'object',
              fields:
                [
                  { label: 'Image', name: 'image', widget: 'image' },
                  {
                    label: 'Image Description',
                    name: 'imageAlt',
                    widget: 'string',
                  },
                ],
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - {
              label: 'Image Gallery',
              name: 'gallery',
              widget: 'list',
              fields:
                [
                  { label: 'Image', name: 'image', widget: 'image' },
                  {
                    label: 'Image Description',
                    name: 'imageAlt',
                    widget: 'string',
                  },
                ],
            }
          - {
              label: 'Developer Groups',
              name: 'developerGroups',
              widget: 'markdown',
            }
          - {
              label: 'Workshop Organizers',
              name: 'organizers',
              widget: 'object',
              fields:
                [
                  { label: 'Title', name: 'title', widget: 'string' },
                  {
                    label: 'Images',
                    name: 'gallery',
                    widget: 'list',
                    fields:
                      [
                        { label: 'Name', name: 'name', widget: 'string' },
                        { label: 'Image', name: 'image', widget: 'image' },
                        {
                          label: 'Image Description',
                          name: 'imageAlt',
                          widget: 'string',
                        },
                      ],
                  },
                ],
            }
          - {
              label: 'SEO & Meta',
              name: 'seo',
              widget: 'object',
              fields:
                [
                  {
                    label: 'Browser Tab Title',
                    name: 'browserTitle',
                    widget: 'string',
                  },
                  { label: 'Title', name: 'title', widget: 'string' },
                  {
                    label: 'Description',
                    name: 'description',
                    widget: 'string',
                  },
                ],
            }
      - file: 'website/src/pages/pastWorkshops/index.md'
        label: 'Past Workshops'
        name: 'pastWorkshops'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'past-workshops-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - {
              label: 'SEO & Meta',
              name: 'seo',
              widget: 'object',
              fields:
                [
                  {
                    label: 'Browser Tab Title',
                    name: 'browserTitle',
                    widget: 'string',
                  },
                  { label: 'Title', name: 'title', widget: 'string' },
                  {
                    label: 'Description',
                    name: 'description',
                    widget: 'string',
                  },
                ],
            }
      - file: 'website/src/pages/home/index.md'
        label: 'Home'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home-page',
            }
          - {
              label: 'Header Image',
              name: 'logoImage',
              widget: 'object',
              fields:
                [
                  { label: 'Image', name: 'image', widget: 'image' },
                  {
                    label: 'Image Description',
                    name: 'imageAlt',
                    widget: 'string',
                  },
                ],
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              label: Google Meta Data,
              name: meta,
              widget: object,
              collapsed: true,
              fields:
                [
                  { label: Meta Title, name: metaTitle, widget: text },
                  {
                    label: Meta Description,
                    name: metaDescription,
                    widget: text,
                  },
                  { label: Robots, name: robots, widget: text },
                ],
            }
          - {
              label: 'Upcoming Workshop Heading',
              name: 'upcomingWorkshopHeading',
              widget: 'string',
            }
          - {
              label: 'No Upcoming Workshop Text',
              name: 'noUpcomingWorkshopText',
              hint: 'This text will be displayed when there are no upcoming workshops',
              required: true,
              widget: 'string',
            }
          - {
              label: 'Maps Note',
              name: 'mapsNote',
              required: true,
              widget: 'string',
            }
          - {
              label: 'Call to Actions',
              name: 'callToActions',
              required: true,
              widget: 'object',
              fields:
                [
                  {
                    label: 'First CTA',
                    name: 'firstCTA',
                    required: true,
                    widget: 'object',
                    fields:
                      [
                        { label: 'Heading', name: 'heading', widget: 'string' },
                        {
                          label: 'Sub Heading',
                          name: 'subHeading',
                          widget: 'string',
                        },
                        {
                          label: 'Link Type',
                          name: 'linkType',
                          widget: 'select',
                          options: ['internal', 'external'],
                        },
                        {
                          label: 'Link URL',
                          name: 'linkURL',
                          widget: 'string',
                          hint: 'Use a relative URL (e.g. /about) if the link is an internal link.',
                        },
                      ],
                  },
                  {
                    label: 'Second CTA',
                    name: 'secondCTA',
                    required: true,
                    widget: 'object',
                    fields:
                      [
                        { label: 'Heading', name: 'heading', widget: 'string' },
                        {
                          label: 'Sub Heading',
                          name: 'subHeading',
                          widget: 'string',
                        },
                        {
                          label: 'Link Type',
                          name: 'linkType',
                          widget: 'select',
                          options: ['internal', 'external'],
                        },
                        {
                          label: 'Link URL',
                          name: 'linkURL',
                          widget: 'string',
                          hint: 'Use a relative URL (e.g. /about) if the link is an internal link.',
                        },
                      ],
                  },
                ],
            }
          - {
              label: 'SEO & Meta',
              name: 'seo',
              widget: 'object',
              fields:
                [
                  {
                    label: 'Browser Tab Title',
                    name: 'browserTitle',
                    widget: 'string',
                  },
                  { label: 'Title', name: 'title', widget: 'string' },
                  {
                    label: 'Description',
                    name: 'description',
                    widget: 'string',
                  },
                ],
            }
  - name: 'navbarAndFooter'
    label: 'Navbar & Footer'
    files:
      - file: 'website/src/pages/navbar/index.md'
        label: 'Navbar'
        name: 'navbar'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'navbar',
            }
          - {
              label: 'Menu Items',
              name: 'menuItems',
              widget: 'list',
              fields:
                [
                  { label: 'Label', name: 'label', widget: 'string' },
                  {
                    label: 'Link Type',
                    name: 'linkType',
                    widget: 'select',
                    options: ['internal', 'external'],
                  },
                  {
                    label: 'Link URL',
                    name: 'linkURL',
                    widget: 'string',
                    hint: 'Use a relative URL (e.g. /about) if the link is an internal link.',
                  },
                ],
            }
      - file: 'website/src/pages/footer/index.md'
        label: 'Footer'
        name: 'footer'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'footer',
            }
          - {
              label: 'Logo Image & Tagline',
              name: 'logoImage',
              widget: 'object',
              fields:
                [
                  { label: 'Image', name: 'image', widget: 'image' },
                  {
                    label: 'Image Description',
                    name: 'imageAlt',
                    widget: 'string',
                  },
                  { label: 'Tagline', name: 'tagline', widget: 'string' },
                ],
            }
          - {
              label: 'Social Links',
              name: 'socialLinks',
              widget: 'list',
              fields:
                [
                  { label: 'Image', name: 'image', widget: 'image' },
                  {
                    label: 'Image Description',
                    name: 'imageAlt',
                    widget: 'string',
                  },
                  { label: 'Label', name: 'label', widget: 'string' },
                  { label: 'Link URL', name: 'linkURL', widget: 'string' },
                ],
            }
